name: Extract Bera Testnet Tokens

on:
    # schedule:
    #     - cron: "0 */6 * * *"
    workflow_dispatch:

jobs:
    extract-bera-token:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .

            - name: Run Python script
              env:
                  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  ERC20_ADDRESSES: ${{ secrets.ERC20_ADDRESSES }}
                  BERA_FAUCET_URL: ${{ secrets.BERA_FAUCET_URL }}
              run: |
                  python -m src.faucet_extractor_poc.extract --faucet BERA
