name: Extract Monad Testnet Tokens

on:
    # schedule:
    #     - cron: "0 */6 * * *"
    workflow_dispatch:

jobs:
    extract-monad-token:
        runs-on: ubuntu-latest
        environment:
            name: ${{ github.ref == 'refs/heads/main' && 'release' || 'staging' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .

            - name: Run Python script
              env:
                  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  ERC20_ADDRESSES: ${{ secrets.ERC20_ADDRESSES }}
                  MONAD_FAUCET_URL: ${{ secrets.MONAD_FAUCET_URL }}
              run: |
                  python -m src.faucet_extractor_poc.extract --faucet MON

            - name: Upload logs as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: monad-logs
                  path: logs/
