name: Bump Version on Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Need this to be able to commit back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract version from tag
        id: get_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # Remove 'v' prefix if present
          VERSION=${TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"
      
      - name: Update version in setup.py
        run: |
          sed -i "s/version=\"[^\"]*\"/version=\"$VERSION\"/" setup.py
          cat setup.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add setup.py
          git commit -m "Bump version to $VERSION [skip ci]"
          git push